use adw::prelude::*;
use podcasts_data::Episode;
use relm4::{Component, ComponentParts, factory::FactoryVecDeque};

use crate::components::episode_list_item::EpisodeListItem;

#[derive(Debug)]
pub struct GroupedEpisodes {
    group_title: String,
    episodes: FactoryVecDeque<EpisodeListItem>,
}

#[derive(Debug)]
pub enum GroupedEpisodesInput {
    AppendEpisodes(Vec<Episode>),
}

#[derive(Debug)]
pub enum GroupedEpisodesOutput {
    // TogglePlay(String),
    // RequestDownload(String),
    // CancleDownload(String),
    // NotifyError(String),
}

#[relm4::component(pub)]
impl Component for GroupedEpisodes {
    type Init = (i32, Vec<Episode>);
    type Input = GroupedEpisodesInput;
    type Output = GroupedEpisodesOutput;
    type CommandOutput = ();

    view! {
        // gtk::Box {
        //     set_orientation: gtk::Orientation::Vertical,
        //     set_spacing: 10,
        //     set_hexpand: true,
        //     set_vexpand: true,


        //     gtk::Label {
        //         set_label: &model.group_title,
        //     },

        adw::PreferencesGroup{
            set_title: &model.group_title,

            // Pass the local reference to the listbox generated by the factory
            #[local_ref]
            episodes_widget -> gtk::ListBox {
                add_css_class: "boxed-list",
                set_vexpand: true,
            },
        }

        //     gtk::Label {
        //         set_label: "hey",
        //     },
        // }
    }

    fn init(
        (year, episodes_list): Self::Init,
        root: Self::Root,
        sender: relm4::prelude::ComponentSender<Self>,
    ) -> relm4::prelude::ComponentParts<Self> {
        let model = Self {
            group_title: format!("{year}"),
            episodes: FactoryVecDeque::builder()
                .launch(gtk::ListBox::builder().build())
                .detach(),
        };

        let episodes_widget = model.episodes.widget();

        let widgets = view_output!();

        sender.input(GroupedEpisodesInput::AppendEpisodes(episodes_list));

        ComponentParts { model, widgets }
    }

    fn update_with_view(
        &mut self,
        widgets: &mut Self::Widgets,
        message: Self::Input,
        sender: relm4::prelude::ComponentSender<Self>,
        _root: &Self::Root,
    ) {
        match message {
            GroupedEpisodesInput::AppendEpisodes(episodes) => {
                let mut guard = self.episodes.guard();
                guard.clear();
                for episode in episodes {
                    guard.push_back(episode);
                }
            }
        }

        self.update_view(widgets, sender);
    }
}
